// Default portfolio data seeded when DB is empty
export const getDefaultPortfolioData = () => ({
  hero: {
    name: "Shivam Pandey",
    tagline: "Full-Stack Developer | MERN Stack | NPM Open Source Contributor",
    description: "Full-Stack Developer with 1+ year of experience building production-grade MERN Stack apps. NPM Verified Open Source Contributor with 1,400+ weekly active users.",
    profilePhoto: "",
    roles: ["Full Stack Developer", "MERN Stack Developer", "NPM Open Source Contributor", "Problem Solver"],
    stats: [
      { number: "5+", label: "Projects Deployed" },
      { number: "1+", label: "Years Experience" },
      { number: "1400+", label: "NPM Weekly Users" },
      { number: "2", label: "NPM Packages" },
    ],
    techStack: [
      { name: "React", color: "#61DAFB" },
      { name: "Node.js", color: "#68A063" },
      { name: "MongoDB", color: "#47A248" },
      { name: "Express", color: "#FFFFFF" },
      { name: "Redis", color: "#FF4438" },
      { name: "AWS EC2", color: "#FF9900" },
      { name: "JWT", color: "#FB015B" },
      { name: "Docker", color: "#2496ED" },
    ],
    socialLinks: [
      { name: "GitHub", href: "https://github.com/Shivam-75" },
      { name: "LinkedIn", href: "https://www.linkedin.com/in/shivam-75github" },
      { name: "Email", href: "mailto:shivam6386000621@gmail.com" },
      { name: "NPM", href: "https://www.npmjs.com/~shivam-75" },
    ],
    githubUrl: "https://github.com/Shivam-75",
    linkedinUrl: "https://www.linkedin.com/in/shivam-75github",
    email: "shivam6386000621@gmail.com",
    phone: "+91-6386000621",
  },
  about: {
    bio: "Hello! I'm Shivam Pandey, a Full-Stack Developer based in Gorakhpur, India. I specialize in building production-grade web applications using the MERN stack (MongoDB, Express.js, React.js, Node.js).",
    bio2: "I'm an NPM Verified Open Source Contributor maintaining two published packages with 1,400+ weekly active users. I have demonstrated expertise in RESTful API design, JWT & OAuth 2.0 authentication, Redis caching (40% load reduction), role-based access control (RBAC), and microservices architecture.",
    bio3: "I have hands-on cloud deployment experience with AWS EC2, Elastic Load Balancer (ELB), Auto Scaling Group (ASG), and Docker. Proficient in AI-assisted development using Generative AI, Prompt Engineering, and Cursor AI.",
    skills: [
      { name: "React / Next.js", level: 90, color: "from-blue-500 to-cyan-400" },
      { name: "JavaScript (ES6+) / Core Java", level: 88, color: "from-yellow-400 to-orange-400" },
      { name: "Node.js / Express", level: 88, color: "from-green-400 to-emerald-500" },
      { name: "MongoDB / MySQL / Redis", level: 82, color: "from-purple-400 to-pink-400" },
      { name: "AWS EC2 / ELB / ASG / Docker", level: 75, color: "from-orange-400 to-amber-400" },
      { name: "JWT / OAuth 2.0 / RBAC", level: 85, color: "from-cyan-400 to-blue-500" },
    ],
    tools: [
      { name: "VS Code", icon: "💻", desc: "Primary IDE" },
      { name: "Figma", icon: "🎨", desc: "UI/UX Design" },
      { name: "Postman", icon: "📮", desc: "API Testing" },
      { name: "GitHub", icon: "🐙", desc: "Version Control" },
      { name: "AWS Console", icon: "☁️", desc: "Cloud Deployment" },
      { name: "Docker", icon: "🐳", desc: "Containerization" },
      { name: "Render / Vercel", icon: "▲", desc: "Hosting" },
      { name: "Gemini API", icon: "🤖", desc: "AI Integration" },
    ],
    timeline: [
      { year: "Jan 2026", title: "ERP Operations Assistant", desc: "Administered academic ERP system at Institute of Technology and Management handling 1,000+ student records with 99% data integrity." },
      { year: "May 2026", title: "Cloudonix – Cloud Media Platform", desc: "Full-stack cloud media management platform with Redis caching (40% load reduction) and JWT + RBAC security." },
      { year: "Nov 2025", title: "NPM Author – crt-server", desc: "Authored and maintain a Node.js CLI package with 1,400+ weekly active users; auto-scaffolds production-ready backend architecture." },
    ],
    quickInfo: [
      { label: "Name", value: "Shivam Pandey", icon: "👤" },
      { label: "Location", value: "Gorakhpur, UP, India", icon: "📍" },
      { label: "Experience", value: "1+ Year", icon: "💼" },
      { label: "Availability", value: "Open to Work", icon: "✅" },
      { label: "Education", value: "BCA – Computer Science", icon: "🎓" },
      { label: "Contact", value: "+91-6386000621", icon: "📞" },
    ],
  },
  projects: [
    { title: "Cloudonix", description: "Full-stack cloud media management platform supporting image, video, and PDF upload with automatic URL generation, processing 500+ assets with third-party API integration.", tags: ["React.js", "Node.js", "MongoDB", "Redis", "JWT", "REST API", "Cloudflare", "Render"], category: "Full Stack", color: "from-blue-500/20 to-cyan-500/20", accent: "#60A5FA", github: "https://github.com/Shivam-75", live: "#", period: "May – Jun 2026" },
    { title: "Gate Entry System – Parampara Fest", description: "QR-code-based gate entry system with 2-factor verification and 3-tier RBAC panels deployed on AWS EC2. Scaled to handle 7,000+ concurrent student verifications.", tags: ["MERN Stack", "JWT", "RBAC", "AWS EC2", "ELB", "ASG"], category: "Full Stack", color: "from-purple-500/20 to-pink-500/20", accent: "#A78BFA", github: "https://github.com/Shivam-75", live: "#", period: "Feb – Mar 2026" },
    { title: "Food Token System – Parampara Fest", description: "QR-based digital food token system eliminating 100% duplicate meal access for 7,000+ students across 3 vendor stations. 3-panel RBAC system reducing manual processing by 60%.", tags: ["MERN Stack", "JWT", "RBAC", "AWS EC2", "ELB", "ASG"], category: "Full Stack", color: "from-emerald-500/20 to-teal-500/20", accent: "#34D399", github: "https://github.com/Shivam-75", live: "#", period: "Feb – Mar 2026" },
    { title: "SaveLife & MediaAssist AI", description: "End-to-end blood bank management system with AI-powered donor-recipient matching via Gemini API, reducing manual matching time by 70%.", tags: ["MERN Stack", "JWT", "Gemini API", "REST API", "MongoDB"], category: "Full Stack", color: "from-rose-500/20 to-red-500/20", accent: "#FB7185", github: "https://github.com/Shivam-75", live: "#", period: "Nov – Dec 2025" },
    { title: "npm i cloudonix", description: "Published open-source Node.js SDK abstracting cloud media upload and URL generation APIs. Earned NPM Verified Contributor badge.", tags: ["Node.js", "Cloud SDK", "REST API Wrapper", "Open Source", "NPM"], category: "Backend", color: "from-orange-500/20 to-yellow-500/20", accent: "#FB923C", github: "https://github.com/Shivam-75", live: "https://www.npmjs.com/package/cloudonix", period: "May – Jun 2026" },
    { title: "npx crt-server", description: "Authored and maintain a Node.js CLI package with 1,400+ weekly active users; auto-scaffolds production-ready backend architecture.", tags: ["Node.js", "CLI Tool", "Open Source", "NPM", "Author & Maintainer"], category: "Backend", color: "from-sky-500/20 to-indigo-500/20", accent: "#38BDF8", github: "https://github.com/Shivam-75", live: "https://www.npmjs.com/package/crt-server", period: "Nov – Dec 2025" },
  ],
  education: [
    { degree: "Bachelor of Computer Applications (BCA)", field: "Computer Science", institution: "Institute of Technology and Management, Gorakhpur", period: "Aug 2023 – Jun 2026", status: "Completed", grade: "7.0/10 CGPA", color: "from-blue-500 to-cyan-400", bgColor: "from-blue-500/10 to-cyan-500/10", icon: "🎓", highlights: ["Data Structures & Algorithms", "Web Development", "Database Management Systems", "Object-Oriented Programming", "Computer Networks"] },
    { degree: "Higher Secondary (12th)", field: "Science - PCB", institution: "SKSD Public School", period: "2021 – 2023", status: "Completed", grade: "%", color: "from-purple-500 to-pink-400", bgColor: "from-purple-500/10 to-pink-500/10", icon: "📚", highlights: ["Physics, Chemistry, Biology", "Computer Science", "National Level Competitions"] },
  ],
  certifications: [
    { name: "NPM Verified Contributor (2025)", issuer: "NPM Registry", year: "2025", icon: "🏆" },
    { name: "Parampara Fest Technical Award", issuer: "Institute of Technology & Management", year: "2026", icon: "🏅" },
    { name: "Gate Entry System – Production Award", issuer: "Parampara Fest (7,000+ users)", year: "2026", icon: "🔐" },
    { name: "Food Token System – Production Award", issuer: "Parampara Fest (7,000+ students)", year: "2026", icon: "🍽️" },
  ],
  codingStats: [
    { number: "1,400+", label: "NPM Weekly Downloads" },
    { number: "4+", label: "Production Systems" },
    { number: "7,000+", label: "Users Served (Fest)" },
    { number: "2", label: "NPM Packages" },
  ],
  services: [
    { title: "Web Development", description: "Building modern, responsive, and high-performance web applications using cutting-edge technologies like React, Next.js, and Node.js.", features: ["Single Page Apps", "Progressive Web Apps", "Server-Side Rendering", "API Development"], color: "from-blue-500 to-cyan-400", bgColor: "from-blue-500/10 to-cyan-500/10", borderHover: "hover:border-blue-500/30" },
    { title: "Backend Solutions", description: "Developing robust, scalable server-side solutions with secure authentication, database management, and cloud deployment.", features: ["REST APIs", "Database Design", "JWT Authentication", "AWS Cloud Deploy"], color: "from-emerald-500 to-teal-400", bgColor: "from-emerald-500/10 to-teal-500/10", borderHover: "hover:border-emerald-500/30" },
    { title: "Open Source & NPM", description: "Creating and maintaining production-quality open-source npm packages with active community adoption and documentation.", features: ["NPM Package Development", "CLI Tools", "SDK Development", "Community Support"], color: "from-purple-500 to-pink-400", bgColor: "from-purple-500/10 to-pink-500/10", borderHover: "hover:border-purple-500/30" },
    { title: "Cloud & DevOps", description: "Deploying and managing applications on AWS with load balancing, auto-scaling, and containerization using Docker.", features: ["AWS EC2 & ELB", "Auto Scaling Groups", "Docker Containers", "CI/CD Pipeline"], color: "from-orange-500 to-yellow-400", bgColor: "from-orange-500/10 to-yellow-500/10", borderHover: "hover:border-orange-500/30" },
  ],
  contact: {
    email: "shivam6386000621@gmail.com",
    phone: "+91-6386000621",
    location: "Gorakhpur, Uttar Pradesh, India",
    available: true,
    availabilityText: "I'm currently available for freelance work and full-time opportunities. Let's build something amazing together!",
  },
  navbar: {
    brandName: "Shivam",
    links: ["Home", "About", "Project", "Service", "Education", "Resume"],
  },
  resume: {
    pdfUrl: "",
  },
});
